# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DualDockerDialog
                                 A QGIS plugin
 This plugin creates an extra window to dock your panels on a second monitor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-11
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Emiel Verstegen
        email                : emiel@verstegen.email
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

import logging
from qgis.core import QgsMessageLog, Qgis

from PyQt5.QtWidgets import QDockWidget, QToolBar, QPushButton
from PyQt5.QtCore import QEvent, QDataStream, Qt
from PyQt5.QtGui import QCursor
from qgis.PyQt.QtWidgets import QApplication


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dual_docker_dialog_base.ui'))


class DualDockerDialog(QtWidgets.QMainWindow, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""

        logging.info("Starting Dual Docker")
        QgsMessageLog.logMessage("Initializing", 'DualDocker', level=Qgis.Info)

        super(DualDockerDialog, self).__init__(parent)
        self.setupUi(self)

        QApplication.instance().installEventFilter(self)


